# Generated by Django 5.2.7 on 2026-04-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='photo_verification_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='photo_verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='photo_verification_status',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
