# Generated by Django 5.2.7 on 2026-04-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_application_photo_verification_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='photo_verification_details',
        ),
        migrations.RemoveField(
            model_name='application',
            name='photo_verification_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='photo_verification_status',
        ),
    ]
