# Generated by Django 5.2.7 on 2026-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
