# Generated by Django 5.2.7 on 2026-04-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsettings', '0034_systemsettings_ip_whitelist_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='verified_only_true',
            field=models.BooleanField(default=False, help_text='If enabled, applications can only be approved if all documents are verified.', verbose_name='Verified Only True'),
        ),
    ]
