# Generated by Django 5.2.7 on 2026-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerships', '0012_remove_partnership_download_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershipdocument',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
